import{a as v,S as q,i as a}from"./assets/vendor-C9jUDwr_.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const P="52827069-8d460a0c946a5f422e59aa590",B="https://pixabay.com/api/";async function u(t,o=1){const n={key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await v.get(B,{params:n})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more"),E=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(t){const o=t.map(({largeImageURL:n,webformatURL:i,tags:e,likes:r,views:s,comments:w,downloads:b})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${i}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
        <p>👍 ${r}</p>
        <p>👁️ ${s}</p>
        <p>💬 ${w}</p>
        <p>⬇️ ${b}</p>
      </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",o),E.refresh()}function M(){f.innerHTML=""}function g(){h.classList.remove("hidden")}function y(){h.classList.add("hidden")}function L(){m.classList.remove("hidden")}function l(){m.classList.add("hidden")}function R(){const t=document.querySelector(".gallery-item");if(!t)return;const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}const $=document.querySelector(".form"),O=document.querySelector(".load-more");let d="",c=1;const S=15;$.addEventListener("submit",x);O.addEventListener("click",A);async function x(t){t.preventDefault();const o=t.target.elements["search-text"].value.trim();if(o){d=o,c=1,M(),l(),g();try{const n=await u(d,c);if(n.hits.length===0){a.info({message:"No images found. Please try another query.",position:"topRight"});return}p(n.hits),n.totalHits<=S?(a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l()):L(),t.target.reset()}catch{a.error({message:"Something went wrong while fetching images.",position:"topRight"})}finally{y()}}}async function A(){l(),g();try{c+=1;const t=await u(d,c);p(t.hits),c*S>=t.totalHits?(a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l()):L(),R()}catch{a.error({message:"Error loading more images.",position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
