import{a as S,S as v,i as a}from"./assets/vendor-C9jUDwr_.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function l(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const q="52827069-8d460a0c946a5f422e59aa590",b="https://pixabay.com/api/";async function f(r,e=1){const o={key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e};return(await S.get(b,{params:o})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more"),E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const e=r.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        </a>
        <div class="info">
        <p>👍 ${o.likes}</p>
        <p>👁️ ${o.views}</p>
        <p>💬 ${o.comments}</p>
        <p>⬇️ ${o.downloads}</p>
      </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",e),E.refresh()}function P(){p.innerHTML=""}function g(){h.classList.remove("hidden")}function c(){h.classList.add("hidden")}function R(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function B(){const e=document.querySelector(".gallery").firstElementChild;if(!e)return;const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}const M=document.querySelector(".search-form"),$=document.querySelector('input[name="query"]'),O=document.querySelector(".load-more");let s="",i=1;const w=15;let u=0;M.addEventListener("submit",H);O.addEventListener("click",x);async function H(r){if(r.preventDefault(),s=$.value.trim(),i=1,P(),L(),!s){a.warning({title:"Oops",message:"Please enter a search query!",position:"topRight"});return}try{g();const e=await f(s,i);if(u=e.totalHits,e.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}y(e.hits),c(),u>w&&R()}catch(e){console.error(e),a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{c()}}async function x(){i+=1,g();try{const r=await f(s,i);y(r.hits),c(),B(),i*w>=u&&(L(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){console.error(r),a.error({title:"Error",message:"Something went wrong while loading more images.",position:"topRight"})}finally{c()}}
//# sourceMappingURL=index.js.map
