import{a as v,S as P,i as s}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const R="52827069-8d460a0c946a5f422e59aa590",B="https://pixabay.com/api/";async function u(t,o=1){const n={key:R,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await v.get(B,{params:n})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".load-more"),E=new P(".gallery a",{captionsData:"alt",captionDelay:250});function m(t){const o=t.map(({largeImageURL:n,webformatURL:i,tags:e,likes:r,views:a,comments:b,downloads:q})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${i}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
        <p>👍 ${r}</p>
        <p>👁️ ${a}</p>
        <p>💬 ${b}</p>
        <p>⬇️ ${q}</p>
      </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",o),E.refresh()}function M(){f.innerHTML=""}function g(){h.classList.remove("hidden")}function y(){h.classList.add("hidden")}function L(){p.classList.remove("hidden")}function c(){p.classList.add("hidden")}function $(){const t=document.querySelector(".gallery-item");if(!t)return;const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}const w=document.querySelector(".form"),O=document.querySelector(".load-more");let d="",l=1;const S=15;w.addEventListener("submit",x);O.addEventListener("click",A);async function x(t){t.preventDefault();const o=t.target.elements["search-text"].value.trim();if(!o){s.warning({message:"Please enter a search query.",position:"topRight"}),c();return}d=o,l=1,M(),c(),g();try{const n=await u(d,l);if(!n.hits.length){s.info({message:"No images found. Please try another query.",position:"topRight"});return}m(n.hits),n.totalHits<=S?(s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c()):L(),t.target.reset()}catch{s.error({message:"Something went wrong while fetching images.",position:"topRight"})}finally{y(),w.reset()}}async function A(){c(),g();try{l+=1;const t=await u(d,l);m(t.hits),l*S>=t.totalHits?(s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c()):L(),$()}catch{s.error({message:"Error loading more images.",position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
